## Exercise 1: NumPy: Create an array with values ranging from 12 to 38

In [2]:
import numpy as np
import time
import sys
array_numpy = np.arange(12,38)
print(array_numpy)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

In [8]:
first_arr = np.ones((2,2)) 
#Zero_arr = np.ones((3,3))
print("Actual Array \n",first_arr)
#print(Zero_arr)
shape = np.shape(first_arr)
print("Shape: \n", shape)
padded_array = np.pad(first_arr, (1, 1))
#padded_array = np.zeros((3,3))
#padded_array[:shape[1],:shape[1]] = first_arr
print("Padded Array :\n", padded_array)

Actual Array 
 [[1. 1.]
 [1. 1.]]
Shape: 
 (2, 2)
Padded Array :
 [[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


## Exercise 3: Convert a list and tuple into arrays

In [69]:
lst = (1, 2, 3, 4 ,5, 6, 7, 8)
print(lst)
lstToArr = np.asarray(lst)
print(lstToArr)
lstToArr.reshape(2,4)

(1, 2, 3, 4, 5, 6, 7, 8)
[1 2 3 4 5 6 7 8]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [10]:
Fahren = np.array(([0,12,45.21,34,99.91]))
print(Fahren)
type(Fahren)
print("Fahrenheit", Fahren)
# using formulae
Centigrade = (5/9 * (Fahren -32))
  
# printing results
print(f"Centigrade {Centigrade}")

[ 0.   12.   45.21 34.   99.91]
Fahrenheit [ 0.   12.   45.21 34.   99.91]
Centigrade [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [12]:
eleArray =  np.arange(3)
print(eleArray)
arrSize = len(eleArray)
print("Size of the array:" ,arrSize )

for oneArr in eleArray:
    print("Length of one array element in bytes :",oneArr.itemsize)
''' OR. print( arry.itemsize)'''    
print (eleArray.nbytes)

'''Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24'''

[0 1 2]
Size of the array: 3
Length of one array element in bytes : 8
Length of one array element in bytes : 8
Length of one array element in bytes : 8
24


'Size of the array:  3\nLength of one array element in bytes:  8\nTotal bytes consumed by the elements of the array:  24'

## Exercise 6: Get the unique elements of an array

In [132]:
OriginalArr = np.array([10 ,10, 20 ,20, 30, 30])
print("OriginalArr: ",OriginalArr)
uniqueArr = np.unique(OriginalArr)
print("uniqueArr: ", uniqueArr)

OriginalArr:  [10 10 20 20 30 30]
uniqueArr:  [10 20 30]


## Exercise 7: Change the dimension of an array


In [140]:
actualDim = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("actualDim:", actualDim)
reshapedarr = actualDim.reshape(3,3)
print("reshapedarr: \n",reshapedarr)


actualDim: [1 2 3 4 5 6 7 8 9]
reshapedarr: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [157]:
OneDim30 = np.linspace(2.5,6.5,30)
print("30 Evenly" ,OneDim30)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [179]:
oneArr1 =  np.array([10,20,30])
Arr2 = np.array([40,50,60])

TwoDim = np.array([oneArr1 , Arr2])
print("TwoDim", TwoDim)
TwoDim.reshape(2,3)
print(TwoDim)
'''Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]'''

TwoDim [[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]


'Array1: [10 20 30]\nArray2: [40 50 60]\nConverted array\n[[10 40]\n [20 50]\n [30 60]]'

## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [197]:
arr0To4 = np.zeros(25)
reshape =arr0To4.reshape(5,5)
print(reshape)
'''Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]'''

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


'Original array:\n[[0. 0. 0. 0. 0.]\n [0. 0. 0. 0. 0.]\n [0. 0. 0. 0. 0.]\n [0. 0. 0. 0. 0.]\n [0. 0. 0. 0. 0.]]\nRow values ranging from 0 to 4.\n[[0. 1. 2. 3. 4.]\n [0. 1. 2. 3. 4.]\n [0. 1. 2. 3. 4.]\n [0. 1. 2. 3. 4.]\n [0. 1. 2. 3. 4.]]'

## Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [213]:
Sumrange100 = np.arange(3,100)

sum =0 
"""for eachelemnt in Sumrange100:
    print(sum + eachelemnt )"""
total = np.sum(Sumrange100)
print (total)
'''[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318'''



4947


'[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51\n 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]\n2318'

## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [16]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


In [28]:
x = np.arange(4)
print("One Dimensional Array : \n", x)
y = np.arange((8))
y = y.reshape(2,4)
print("Two Dimensional Array : \n", y)

for a,b in np.nditer([x,y]):
    print(a,":",b)

One Dimensional Array : 
 [0 1 2 3]
Two Dimensional Array : 
 [[0 1 2 3]
 [4 5 6 7]]
0 : 0
1 : 1
2 : 2
3 : 3
0 : 4
1 : 5
2 : 6
3 : 7


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [73]:
x = np.array([[0.42436315,0.48558583,0.32924763],[0.7439979 ,0.58220701,0.38213418],[0.5097581 , 0.34528799 ,0.1563123]])
#x = np.array([[0.42436315,0.48558583,0.3292476],[0.7439979 ,0.58220701,0.38213418],])
#print(x)
for i in x:
    print(i)
    for j in range(0,len(i)):
        #print(i[j])
        if (i[j] > 0.5):
            i[j] = 0.5
        else:
            i[j] = i[j] 
        #if(j[i] >= 0.5):
            #j[i] = j[i]  
        

[0.42436315 0.48558583 0.32924763]
[0.7439979  0.58220701 0.38213418]
[0.5097581  0.34528799 0.1563123 ]


In [94]:
x = np.array([[0.42436315,0.48558583,0.32924763],[0.7439979 ,0.58220701,0.38213418],[0.5097581 , 0.34528799 ,0.1563123]])
#x = np.array([[0.42436315,0.48558583,0.3292476],[0.7439979 ,0.58220701,0.38213418],])
print("Original array: \n",x)
for idx1,i in enumerate(x):
    #print(i)
    for idx,j in enumerate(i):
        #print(idx,j)
        #print("printing based on index :\n", x[idx,idx1])
        if (j > 0.5):
            x[idx,idx1] = 0.5 
        #print("printing after the assigment :\n", x[idx,idx1])
        

print("Replace all elements of the said array with .5 which are greater than .5 \n",x)

Original array: 
 [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5 
 [[0.42436315 0.5        0.5       ]
 [0.7439979  0.5        0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]


Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 14: Add a new row to an empty numpy array

In [111]:
A = np.array([])
type(A)
print("Empty array: \n",A)
A = np.array([[10,20,30],[40, 50 ,60]])
print("After adding two new arrays: \n",A)

Empty array: 
 []
After adding two new arrays: 
 [[10 20 30]
 [40 50 60]]


Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

In [199]:
A1 = np.array([1,2,3])
A2 = np.array([2, 3 ,4])
print("Original arrays: \n")
print(A1,"\n")
print(A2,"\n")

seqArr1 = np.stack((A1,A2),axis = 0)
print("Sequence of arrays along a new axis: \n\n",seqArr1, "\n")
B = np.array([[1],[2],[3]])
C = np.array([[2],[3],[4]])
print(B,"\n")
print(C,"\n")
seqArr = np.stack((B,C), axis=1)
seqArrblk = np.stack([B,C],axis =2).reshape(6)

print("Sequence of arrays along a new axis: \n",seqArrblk)

Original arrays: 

[1 2 3] 

[2 3 4] 

Sequence of arrays along a new axis: 

 [[1 2 3]
 [2 3 4]] 

[[1]
 [2]
 [3]] 

[[2]
 [3]
 [4]] 

Sequence of arrays along a new axis: 
 [1 2 2 3 3 4]


Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
