# How to create a series from a list, numpy array and dict

In [19]:
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [16]:
mydict = set(zip(mylist,myarr))
print(mydict)

{('r', 17), ('y', 24), ('i', 8), ('c', 2), ('k', 10), ('x', 23), ('d', 4), ('v', 21), ('w', 22), ('b', 1), ('p', 15), ('s', 18), ('u', 20), ('n', 13), ('q', 16), ('f', 5), ('j', 9), ('e', 3), ('o', 14), ('a', 0), ('t', 19), ('g', 6), ('m', 12), ('z', 25), ('h', 7), ('l', 11)}


In [27]:
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
print(ser3.head())


a    0
b    1
c    2
e    3
d    4
dtype: int64


# How to convert the index of a series into a column of a dataframe?


In [42]:
mylist = list('abcdefghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
df1 = pd.DataFrame(ser)
df = ser.to_frame().reset_index()
df

index   0
0      a   0
1      b   1
2      c   2
3      d   3
4      e   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

# How to combine many series to form a dataframe

In [37]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

# Solution 1 :

In [464]:
df = pd.concat([ser1,ser2],axis =0)
df

0    1
1    2
2    3
3    4
4    5
0    4
1    5
2    6
3    7
4    8
dtype: int64

# Solution 2

In [51]:
df = pd.DataFrame({'col1':ser1,'col2': ser2})
print(df.head())


  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4


In [76]:
df.loc[0:1,'col1']

0    a
1    b
Name: col1, dtype: object

In [87]:
df.iloc[1:2,0:2] # access the data based on the index so tht it will execude end point. as you you can difference between result loc and iloc 

col1  col2
1    b     1

# How to assign name to the series’ index?

In [94]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

In [96]:
ser.name = 'alphabets'
ser

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: alphabets, dtype: object

In [97]:
ser.name

'alphabets'

# How to get the items of series A not present in series B

In [125]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser3 = []

In [102]:
ser1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [119]:
for i in ser1:
    if (i  in ser2):
        ser3.append(i)
        
        
ser3

[1, 2, 3, 4]

In [132]:
list(~ser1.isin(ser2))
[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

 # How to get the items not common to both series A and series B

In [134]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])


In [139]:
ser_u = pd.Series(np.union1d(ser1, ser2))  # union
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
ser_u[~ser_u.isin(ser_i)]


0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [138]:
ser_i

0    4
1    5
dtype: int64

In [140]:
df.iloc[::46, :]

col1  col2
0    a     0

In [238]:
df = pd.DataFrame(np.random.randint(1, 50,50).reshape(10,-1), columns=list('covid'))
df

c   o   v   i   d
0  13  32  34  33  23
1   9  44  16  33   3
2  39  38  35  24  34
3  46  28  18  37  25
4  39   3   3   2  11
5  38  42  15  35  10
6  41  29   8  37  19
7   7  33  44   7  39
8  31  26   9  14  46
9   6  14  33  44  37

In [189]:
arr = np.random.randint(1, 50,50)


In [171]:
 what is the difference between arr.reshape(10,-1) and arr.reshape(10,4)

array([[12, 39, 22, 26],
       [ 5, 16, 35, 25],
       [28,  2, 34, 19],
       [26, 31,  1,  7],
       [14, 36, 33, 39],
       [ 4, 25, 29, 25],
       [39, 34, 20, 36],
       [17, 25, 15, 24],
       [ 8, 29, 37, 39],
       [ 7, 10, 28, 19]])

In [193]:
arr.reshape(10,-5)

array([[37, 14, 44, 17, 13],
       [ 3, 38, 46, 43, 48],
       [13, 39, 48, 18,  3],
       [42, 42, 49, 18, 20],
       [35, 15, 42, 34, 32],
       [38, 22, 39, 37,  8],
       [ 7, 27, 46, 44, 21],
       [ 2, 25, 28, 33, 24],
       [17, 28, 28, 14,  5],
       [24, 13, 21, 21, 46]])

In [220]:

df['s']

s   s
0  12   9
1  16  18
2  11  36
3  33  10
4  37   8
5  22  41
6  22  16
7  38  23
8   8  28
9  47  46

In [271]:
df[(df['c'] == 41) | (df['c'] == 39 )].index.values.astype(int)[1]

4

In [260]:
df

c   o   v   i   d
0  13  32  34  33  23
1   9  44  16  33   3
2  39  38  35  24  34
3  46  28  18  37  25
4  39   3   3   2  11
5  38  42  15  35  10
6  41  29   8  37  19
7   7  33  44   7  39
8  31  26   9  14  46
9   6  14  33  44  37

# How to get the last n rows of a dataframe with row sum > 100

In [276]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Solution 
# print row sums

In [298]:
rownums = df.apply(np.sum,axis=1)

In [302]:
rowsum

0     106
1      94
2      98
3      83
4      73
5     129
6      80
7     135
8     128
9     129
10     76
11     97
12     88
13     59
14     80
dtype: int64

In [300]:
rowsum = df.apply(np.sum,axis=1)

In [315]:
last_two_rows = df.iloc[np.where(rowsum > 100)[0][-2:],:]


In [316]:
last_two_rows

0   1   2   3
8  37  19  39  33
9  31  37  30  31

In [318]:
a,b = 12,20

In [319]:
a

12

In [320]:
b

20

# How to replace both the diagonals of dataframe with 0

In [372]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))


In [323]:
df

0   1   2   3   4   5   6   7   8   9
0  85  81  22  61  44  71  75  38  12  35
1  33  32  38  47  67  85  58   4  44  12
2  62  34  75   7  13  55  69  47  81  74
3  19  14  82   7  10  14  66  99  31   9
4  50  23  15  22  79  48  78  50  58  39
5  52  61  72  14  64  21  75   7  54   4
6  12  50   7  87  47  33  36   9  34  91
7  67  76  21  72  23  75  83  42  54  98
8  32  61  27  82  64  28  71  22  43  22
9  21  26   8  92  77  81  80  32  37  93

In [324]:
df

0   1   2   3   4   5   6   7   8   9
0  85  81  22  61  44  71  75  38  12  35
1  33  32  38  47  67  85  58   4  44  12
2  62  34  75   7  13  55  69  47  81  74
3  19  14  82   7  10  14  66  99  31   9
4  50  23  15  22  79  48  78  50  58  39
5  52  61  72  14  64  21  75   7  54   4
6  12  50   7  87  47  33  36   9  34  91
7  67  76  21  72  23  75  83  42  54  98
8  32  61  27  82  64  28  71  22  43  22
9  21  26   8  92  77  81  80  32  37  93

In [389]:
for i in range(df.shape[0]):
    df.iat[i,i] = 0
    df.iat[df.shape[0]-i-1,1] = 0

In [390]:
df

0  1   2   3   4   5   6   7   8   9
0   0  0  78  85  39  19   2  92  51  81
1  54  0  84  79  13  38  65  10   1  32
2  29  0   0  18   4  34  32  47  48  65
3  23  0   1   0  84  24  97  81  19  38
4  58  0  45  24   0  54  34  37  58  71
5   4  0   7  18  99   0  10  66  44  32
6  15  0  30  84  10  66   0  10  95  48
7  28  0  58   7  72  63   7   0  93  44
8  45  0  27  54  30  21  90  48   0  71
9  98  0  54  36  70  84  13   1  27   0

In [387]:
df.iat[df.shape[0]-5-1, 5]

54

In [382]:
 df.iat[1,3]

79

In [348]:
df.iat[df.shape[0]-1-1, 1]

61

In [353]:
df.shape[0]-0-1,1

(9, 1)

# How to get the particular group of a groupby dataframe by key

In [408]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})


In [409]:
df

col1      col2  col3
0   apple  0.907157     5
1  banana  0.967163     9
2  orange  0.080639     0
3   apple  0.141341    11
4  banana  0.502905    12
5  orange  0.336050     4
6   apple  0.508895    14
7  banana  0.356413    10
8  orange  0.366823     0

In [410]:
df_grouped = df.groupby(['col1'])

In [404]:
df_grouped

In [415]:
df_grouped.get_group('orange')


col1      col2  col3
2  orange  0.080639     0
5  orange  0.336050     4
8  orange  0.366823     0

# How to get the n’th largest value of a column when grouped by another column

In [424]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

In [425]:
df

fruit     taste  price
0   apple  0.580923     13
1  banana  0.987427      1
2  orange  0.854112      8
3   apple  0.931375     11
4  banana  0.167362      4
5  orange  0.871276      5
6   apple  0.715867      8
7  banana  0.001506      5
8  orange  0.964744      1

In [428]:
df_grpd = df['taste'].groupby(df.fruit)


In [427]:
df_grpd.get_group('banana').sort_values().iloc[-2]


0.16736231737216345

In [446]:
df_grpd.get_group('banana').sort_values().iloc[-2]

0.16736231737216345

In [437]:
df_grpd.get_group('banana').sort_values()

7    0.001506
4    0.167362
1    0.987427
Name: taste, dtype: float64

# How to know the maximum possible correlation value of each column against other columns

In [447]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))


In [448]:
df

p   q   r   s   t   u   v   w   x   y
a   2  14  40  52  15  19  51  21  21   1
b  80  71  78   5  92  44  61  73  81  37
c  60  67  42  54  92  92   4  96  55  57
d  32  86   7  45  24  15  59  99  66  34
e  67  23  89  87  29  54  96  36  66  69
f  70  82  31  61  35  36  43  92  35   7
g  10  86   5  15  33  98  78  81  35  17
h  91  29  80  38  64  83  27  10  76  85

In [454]:
abs_corrmat = np.abs(df.corr())


In [455]:
abs_corrmat

p         q         r         s         t         u         v  \
p  1.000000  0.046980  0.711794  0.084710  0.631500  0.202880  0.271014   
q  0.046980  1.000000  0.641606  0.451170  0.188120  0.091106  0.061972   
r  0.711794  0.641606  1.000000  0.202334  0.414084  0.094919  0.049082   
s  0.084710  0.451170  0.202334  1.000000  0.408018  0.222574  0.057928   
t  0.631500  0.188120  0.414084  0.408018  1.000000  0.483460  0.547495   
u  0.202880  0.091106  0.094919  0.222574  0.483460  1.000000  0.241629   
v  0.271014  0.061972  0.049082  0.057928  0.547495  0.241629  1.000000   
w  0.094700  0.921288  0.622479  0.190383  0.187058  0.006336  0.119514   
x  0.732378  0.022659  0.584953  0.173630  0.577430  0.120471  0.007819   
y  0.675917  0.331060  0.657169  0.194590  0.464870  0.465186  0.164414   

          w         x         y  
p  0.094700  0.732378  0.675917  
q  0.921288  0.022659  0.331060  
r  0.622479  0.584953  0.657169  
s  0.190383  0.173630  0.194590  
t  0.187058  0.577430  0.464870  
u  0.006336  0.120471  0.465186  
v  0.119514  0.007819  0.164414  
w  1.000000  0.048399  0.343035  
x  0.048399  1.000000  0.777800  
y  0.343035  0.777800  1.000000

In [456]:
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])


In [457]:
max_corr

p    0.732378
q    0.921288
r    0.711794
s    0.451170
t    0.631500
u    0.483460
v    0.547495
w    0.921288
x    0.777800
y    0.777800
dtype: float64

In [461]:
np.round(max_corr.tolist(),2)

array([0.73, 0.92, 0.71, 0.45, 0.63, 0.48, 0.55, 0.92, 0.78, 0.78])